### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by AVHon** [wejgaard/Holonforth-GUI#1]
I'd like to try HolonU, but the distributed executables are for 32-bit systems, and I can't figure out how to build and run the source on my 64-bit linux machine. Can you post instructions for that?

I got as far as figuring out that I want to run `tclsh ./Source/holon.vfs/main.tcl`, and that I need to install `tcl-vfs`.

**Comment by wejgaard** [comment]
HolonU was prepared as a tclkit for Linux and did run in Ubuntu 6.06 with: "./tclkit holon.kit holon.hdb"  -- I don't touch Linux anymore. You might find a better tclkit for your machine.

HolonU still runs with the old osx-tclkit in 64 bit macOS.

**Comment by AVHon** [comment]
Ah, the [tclkit](https://equi4.com/tclkit/) dependency wasn't clear to me. [Downloading](https://equi4.com/tclkit/download.html) version 8.5.1 for x86_64b linux, putting it in my path, setting it as executable, and running `tclkit Source/holon.vfs/main.tcl` works for me.

Looking at tclkit's news dates, I'm a little concerned that the last release was 11 years ago (2008-03-11). Is it still a reasonable tool to develop applications in?

**Comment by wejgaard** [comment]
With the tclkit executable you are free of changes in tclsh. So your setup
should be fine for a long time. Enjoy HolonU.

Am Mi., 20. Feb. 2019 um 18:08 Uhr schrieb Alex Von Hoene <
notifications@github.com>:
